In [8]:
import numpy as np
# a = np.array?
# ? next to a method will display the help on that method/function

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [10]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.random.rand(3, 4)

array([[0.17571427, 0.22975357, 0.52581426, 0.60214119],
       [0.3954481 , 0.43577055, 0.25539745, 0.06987345],
       [0.2967575 , 0.59966152, 0.08718209, 0.7628773 ]])

In [17]:
ar1 = np.array([[1, 2, 3], [10, 20, 30]])
ar2 = np.array([5, 5, 5])
ar1 + ar2

array([[ 6,  7,  8],
       [15, 25, 35]])

In [28]:
nums = np.array([12, 10, 5])
np.square(nums)

array([144, 100,  25])

In [29]:
np.sin(nums)

array([-0.53657292, -0.54402111, -0.95892427])

In [30]:
np.exp(nums)

array([1.62754791e+05, 2.20264658e+04, 1.48413159e+02])

In [34]:
nums = np.array([12, 94, 49, 29, 0, 458, 334])
print(np.sum(nums))
print(np.average(nums))
print(np.min(nums))
print(np.max(nums))

976
139.42857142857142
0
458


In [35]:
arr = np.array([[1, 2], [3, 4]])
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# arr[:2, 1:]
# arr[1:, 1:]
arr[1:2, 1:2]

array([[5]])